### ISSUE TITLE
corejam dev watcher error

### ISSUE THREAD

**Issue by mattvb91** [corejam/corejam#2]
When running `corejam dev` inside a plugin and change a shared file or server file the watcher process crashes with:

```
$ corejam dev
  Watching for file change...
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Process already defined
      at Object.set (packages/cli/dist/processes.js:9:15)
      at FSWatcher.<anonymous> (/packages/cli/dist/commands/dev.js:62:41)
      at FSWatcher.emit (events.js:314:20)
      at FSWatcher.emitWithAll (node_modules/chokidar/index.js:534:8)
      at FSWatcher._emit (/node_modules/chokidar/index.js:626:8)
      at FsEventsHandler.handleEvent (node_modules/chokidar/lib/fsevents-handler.js:288:14)
      at FsEventsHandler.addOrChange (node_modules/chokidar/lib/fsevents-handler.js:238:8)
      at watchCallback (node_modules/chokidar/lib/fsevents-handler.js:343:21)
      at filteredListener (node_modules/chokidar/lib/fsevents-handler.js:127:7)
      at node_modules/chokidar/lib/fsevents-handler.js:152:11
} error: Error: Process already defined
```

Looks like some processes are not collected properly into `cli/processes.ts`?

Edit:

```corejam api:dev``` on its own seems to work fine

**Comment by patrickhaug** [comment]
Is fixed with #39

**Comment by mattvb91** [comment]
@patrickhaug still getting the same issue on current master when editing a schema while dev mode is running
